version: "3.7"
services:
  server:
    image: server-heart
    container_name: server-heart
    restart: unless-stopped
    networks:
      - heart-app
    build:
      dockerfile: Dockerfile
      context: "./server"
  client:
    image: client-heart
    container_name: client-heart
    environment:
      - API_URL=/api
    networks:
      - heart-app
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - server
  proxy:
    image: nginx:alpine
    container_name: proxy-heart
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 6000:80
    networks:
      - heart-app
networks:
  heart-app:
    driver: bridge
    
