version: "3.8"
services:
  server:
    image: server-heart
    container_name: server-heart
    restart: unless-stopped
    networks:
      - heart-app
    build:
      dockerfile: Dockerfile
      context: "./server"
  client:
    image: client-heart
    container_name: client-heart
    environment:
      - API_URL=ws://server:2567
    networks:
      - heart-app
      - frontend
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - server
networks:
  heart-app:
    driver: bridge
  frontend:
    external: true
    
