version: "3.7"
services:
  server:
    image: server-heart-image
    container_name: server-heart
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: "./server"
  client:
    image: client-heart-image
    container_name: client-heart
    environment:
      - API_URL=/api
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - server
  proxy:
    image: proxy-heart-image
    container_name: proxy-heart
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: "./proxy"
    ports:
      - 6000:80
    depends_on:
      - client
      - server
